[package]
name = "color_scrape"
version = "0.0.1"
edition = "2021"

[dependencies]
css-color = "0.2.5"
lazy_static = "1.4.0"
regex = "1.7.1"
reqwest = "0.11.14"
scraper = "0.15.0"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["full"] }
